### ISSUE TITLE
Some log entries are not matched by the current regex and so may result in no data being shown

### ISSUE THREAD

**Issue by ProNotion** [DanDiplo/UmbracoTraceLogViewer#11]
Easiest way to replicate this is to create a log file with one or more of these entries:

    2016-01-20 11:11:28,402 [10] WARN  
    Server: NOT AVAILABLE 
    Url: http://NOT AVAILABLENOT AVAILABLE
     Umbraco.Core.Services.ApplicationTreeService - [P12108/T19/D2] The tree definition: <add initialize="true" sortOrder="0" alias="censusTree" application="developer" title="Census" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Census.Controllers.CensusTreeController, Census" /> could not be resolved to a .Net object type

See the following post on the forum for more detail:

https://our.umbraco.org/projects/developer-tools/diplo-trace-log-viewer/diplo-trace-log-viewer/65212-Entries-not-showing

**Comment by DanDiplo** [comment]
Thanks for logging this. I'm going to do what I've been meaning to do for a long time, and that is create some proper unit tests for the project so I can more easily test the parsing. Hopefully this will help fix any issues more easily. It may take a while to refactor everything, though.

If anyone has any ideas about improving the reg ex I'm all ears! :)

**Comment by DanDiplo** [comment]
@ProNotion Does this type of log entry happen often for you? Because the format doesn't seem to match anything that log4net should be logging. I'm not clear where the text "Server: NOT AVAILABLE 
Url: http://NOT AVAILABLENOT AVAILABLE" has come from? I've never seen anything like it any other log files (and I've looked at a lot!).

The log level should just be "WARN" or "ERROR" and not have any more text. Likewise the next entry after that should just be the class that logged the error - in your case `Umbraco.Core.Services.ApplicationTreeService`

@nul800sebastiaan Have you seen anything like this? Is it something that should be happening?

I can probably work around it, but will have to capture "WARN  Server: NOT AVAILABLE  Url: http://NOT AVAILABLENOT AVAILABLE" as the Level field (and then maybe throw away everything after the WARN???)

**Comment by nul800sebastiaan** [comment]
@ProNotion Is "NOT AVAILABLE" something you added to not reveal the actual URL?

**Comment by DanDiplo** [comment]
I've hopefully managed to work around this and tweaked the regex to be a bit more tolerant of edge cases. I've also added a suite of NUnit 3 unit tests to make testing much easier and hopefully ensure it is more robust going forward.

The source should be updated here and I've also pushed a new Nuget package (2.2.4) to Nuget this morning - https://www.nuget.org/packages/DiploTraceLogViewer/2.2.4

I'd be grateful if people could test and let me know if there are any issues (and if you can fix them even better :)).

**Comment by ProNotion** [comment]
Really sorry I've not come back on this yet, I'm snowed under at the moment.

@nul800sebastiaan It's a regular occurrence in at least one of the site. As I am writing this I am thinking what might be common to both sites and it is a customisation of the conversion pattern in log4net.config:

    <conversionPattern value="%date [%thread] %-5level %nServer: %aspnet-request{SERVER_NAME} %nUrl: http://%aspnet-request{HTTP_HOST}%aspnet-request{URL}%n %logger - %message%newline" />

The change should give the url of the page on which the error was logged (if applicable). That said, @DanDiplo for log items like this which might not match the regex (because of customisations) it would be good if it didn't cause all other log items not to be displayed. I will try and test out your update today and let you know how it goes.

**Comment by DanDiplo** [comment]
@ProNotion Did you ever get around to testing?

I think it's going to be very difficult to work around custom log formats. The problem is the log format that Umbraco (log4Net) creates isn't delimited in any obvious manner, so parsing out individual items is pretty difficult - hence the reason I have a 193 character regular expression :) 

I might look in the future to making the regex configurable, but I haven't really encountered many people who have customised the format, so I'm afraid you are a real edge case :)

**Comment by ProNotion** [comment]
I've tested this but no joy unfortunately. I think though that I might remove this change in the log4netconfig for the time being until I can actually resolve why in some cases the url & server do not resolve. It's a load balanced site and this information would be useful but only if it is populated correctly!

A configurable regex would be great for anyone else with custom formats but I understand that it wouldn't be a high priority really given that the majority just probably use the out of the box config.

**Comment by DanDiplo** [comment]
Thanks. Strange it still doesn't show up - I specifically created a Unit test for your example log entry and that passed. See https://github.com/DanDiplo/UmbracoTraceLogViewer/blob/master/Diplo.TraceLogViewer.Tests/Umbraco72xTests.cs 

You don't have Merchello installed, by any chance, do you?

For the next release I'll look at making the regex configurable.
