### ISSUE TITLE
CSS overwrite core styling (dialog)

### ISSUE THREAD

**Issue by bjarnef** [DanDiplo/UmbracoTraceLogViewer#18]
I am using Umbraco as a Service, which include your package.

However it seems that css included in your package overwrite core styling, which cause dialogs to be much wider.

![image](https://cloud.githubusercontent.com/assets/2919859/17587198/fd2a2fea-5fc6-11e6-91d5-23095680a8e5.png)

**Comment by DanDiplo** [comment]
Hi. Yes, it's something I'm aware of. I found the width of the standard umbraco dialogue often caused horizontal scrolling on wider screens when there were long messages. Unfortunately, because of the way the dialogue modal opens, there isn't any way to change this size just for my package (there isn't any wrapper div I can target specific to my package).

So I was left with the choice of either using the standard dialogue, which made reading messages more difficult due to having a horizontal scroll bar, or changing the CSS which could affect all dialogues. I chose the latter. I did try and make my CSS responsive, so it adapted to the size of the screen, which the standard dialogue doesn't do. So it's only bigger on very wide screens. But I can't find a way of making it wider just for my package.

If it's a big issue you can change the CSS, which will be in `/App_Plugins/DiploTraceLogViewer/backoffice/diplotracelog/tracelog.css`

https://github.com/DanDiplo/UmbracoTraceLogViewer/blob/master/Umbraco7.1.3/App_Plugins/DiploTraceLogViewer/backoffice/diplotracelog/tracelog.css

If you've any suggestions on how to make it so the CSS just applies to dialogues my package opens, I'd be happy to incorporate those.

**Comment by bjarnef** [comment]
Ahh okay. Yes, sometimes it would be useful if html or body element has some classes, e.g. current section (e.g. `content`) and/or Umbraco version (e.g. `umb-743`).

Not a big issue and the new `umb-overlay` doesn't use the class `modal`. I think it is when using dialogService like in this case with LeBlender.

**Comment by bjarnef** [comment]
Great! I just noticed it - so thought I would create an issue here to remember to fix it somehow or consider if there should be made a change in core to handle scenarios like this.

**Comment by DanDiplo** [comment]
Just released a new version that should fix. I now use jQuery to add the CSS, so I can target just my modal.
