### ISSUE TITLE
Does not support numbered files when using Composite rolling patterns

### ISSUE THREAD

**Issue by Shazwazza** [DanDiplo/UmbracoTraceLogViewer#26]
When rollingStyle is set to Composite and maxSizeRollBackups and countDirection is used.

This will result in a file name like:

UmbracoTraceLog.helloworld.2016-12-20.1.txt
UmbracoTraceLog.helloworld.2016-12-20.2.txt
UmbracoTraceLog.helloworld.2016-12-20.3.txt

So there could be multiple files for a single day

**Comment by DanDiplo** [comment]
Ahh, OK, wasn't aware of that configuration.  

What is the actual issue? Is it not including the files or is it showing the same date for each file, making them indistinguishable?

**Comment by Shazwazza** [comment]
I haven't tested the issue just looked at the regex statement that is used to match files and it doesn't take that pattern into account. Might also be nice to recognize the .log extension too

**Comment by DanDiplo** [comment]
OK, thanks. Since reporting the issue I released 2.3.2 - https://www.nuget.org/packages/DiploTraceLogViewer/ - which should work OK with the format you posted. The only issue is that it can't parse just the machine name from the file name - but it works. I'll look at taking account of .log as an extension in next release. It may be I just have to give up trying to use regex to validate and match filename and just read in all files in the logs folder.

**Comment by lucasch** [comment]
I wouldn't be against removing the filename matching as this would open up the viewer to handle other log4net files we may drop in the same directory.

**Comment by DanDiplo** [comment]
@lucasch It would only be able to parse log4net files in the same format as Umbraco writes, though.

The reason I had file name matching in the first place was to avoid trying to parse files that weren't from Umbraco and also so I could extract the date / machine name to use in the UI. I could just display a list of filenames rather than dates in the left menu, but then the UI would look like:

- UmbracoTraceLog.322008-app1.txt.2017-01-15
- UmbracoTraceLog.322008-app1.txt.2017-01-14
- UmbracoTraceLog.322008-app1.txt.2017-01-13
etc.
Is that as nice? I'm not sure. Open to suggestions.

**Comment by lucasch** [comment]
@DanDiplo Right, I'm sure we do a lot of things other users don't with our Umbraco installations.  One such thing is to use the log4net tooling in Umbraco to generate logs for other subsystems to separate the bits we want into more concise logs.  In this case, we're doing it for Newsletter Studio, but it could be for Examine indexing or whatever we feel the need to separate logging for.

It could be that our case is such an outlier that this is not even worth bothering with.  I could imagine having a tree node per day, with each log file of that date as a child node under with its label being its filename.  This would work where you're using numbered files and non-patterned filenames, but may get weird if you're not rolling on days.

I'm sort of thinking out loud here, as it were.  You're welcome to disregard (:

**Comment by DanDiplo** [comment]
@lucasch So are your sub-system logs in the same format as the Umbraco logs? If so, makes sense to include them.

I quite like your idea of how the tree works - I've been thinking of something like that. I'll have a think around it.

**Comment by lucasch** [comment]
@DanDiplo Yep, the logs are just specified in the same log4net config with a different set of namespaces to listen on.  The format is identical -- I essentially copied the appender spec from the one already specified by Umbraco in log4net.config, just with a different name and target file name.

**Comment by DanDiplo** [comment]
@Shazwazza @lucasch I've released a beta version on NuGet that I hope you can test:

https://www.nuget.org/packages/DiploTraceLogViewer/2.4.0-beta

This new version will list _all_ files in your `\Logs`\ folder and you can now browse log files by date or by filename. This should allow it to pick up any valid log file, regardless of filename.

Please let me know what you think.
